name: Attach avatars to release assets

on:
  release:
    types:
      - released
      - prereleased

jobs:
  attach_avatar:
    name: Attach avatars to release assets
    needs: get_target_branches
    permissions:
      contents: write
    uses: Gakuto1112/MyFiguraAvatarPacker/.github/workflows/attach_avatars.yml@main
    with:
      target_branches: ${{ needs.get_target_branches.outputs.target_branches }}