name: Attach avatars to release assets

on:
  release:
    types:
      - released
      - prereleased

jobs:
  attach_avatar:
    name: Attach avatars to release assets
    permissions:
      contents: write
    uses: Gakuto1112/MyFiguraAvatarPacker/.github/workflows/attach_avatars.yml@main
    with:
      target_branches: '["<branch_1_name>"]' # ここにリリースアセットに添付するアバターがあるブランチの名前を入力する。
      avatar_names: '{"Avatar_1": "My avatar 1", "Avatar_2": "My avatar 2"}' # ここにアバターの名前を指定することでアバター名を上書きできる。キーをブランチ名に、値をアバター名にする。この引数は省略できる。
      includes: '["sounds"]' # ここにアバターデータに追加で含めたいファイル/ディレクトリ名を指摘できる。この引数は省略できる。
      should_show_branch_name: false # readme内にアバターのブランチ名を記載するかどうか。1つのレポジトリ内でブランチ毎に複数のアバターがある場合は`true`が推奨。この引数は省略できる。