name: Pack my Figura avatar

on:
  push: # この例では、レポジトリにプッシュがあった時にワークフローが実行される。
    branches: # ワークフロー実行対象を特定のブランチのみに絞ることも可能。ワイルドカードも使用可能。
      - Avatar_1
      - Avatar_2

jobs:
  pack_avatar:
    name: Pack Figura avatar
    uses: Gakuto1112/MyFiguraAvatarPacker/.github/workflows/pack_figura_avatar.yml@main
    with:
      target_branch: ${{ github.ref }} # ここに加工するアバターがあるブランチの名前を入力する。この例では、pushイベントがトリガーされたブランチの名前が入る。