name: Attach avatars to release assets

on:
  workflow_call:
    inputs:
      target_branches:
        description: The JSON array of branch names to make an avatar package and attach it to release assets
        type: string
        required: true
      avatar_names:
        description: The JSON key-value object with corresponding branch name and avatar name. Keys are branch names and Values are avatar names.
        type: string
        required: false
        default: '{}'
      includes:
        description: The JSON array of including files/directories
        type: string
        required: false
        default: '[]'
      should_show_branch_name:
        description: Whether branch names are shown in readme.txt or not
        type: boolean
        required: false
        default: false
      update_checker_script_included:
        description: Whether the target avatar has an update checker script
        type: boolean
        required: false
        default: false
      path_to_update_checker:
        description: Path to the update checker script. Required if `update_checker_script_included` is true.
        type: string
        required: false
        default: ''
      should_replace_branch_name:
        description: Whether the branche name field in the update checker script should be repleced to the target avatar's branch name
        type: boolean
        required: false
        default: false

jobs:
  pack_figura_avatar:
    name: Pack my Figura avatars
    strategy:
      matrix:
        target_branch: ${{ fromJSON(inputs.target_branches) }}
    uses: ./.github/workflows/pack_figura_avatar.yml
    with:
      target_branch: ${{ matrix.target_branch }}
      avatar_name: ${{ fromJSON(inputs.avatar_names)[format('{0}', matrix.target_branch)] }}
      includes: ${{ inputs.includes }}
      should_show_branch_name: ${{ inputs.should_show_branch_name }}
      update_checker_script_included: ${{ inputs.update_checker_script_included }}
      path_to_update_checker: ${{ inputs.path_to_update_checker }}
      should_replace_branch_name: ${{ inputs.should_replace_branch_name }}
  attach_avatar:
    name: Attach avatars to release assets
    needs: pack_figura_avatar
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          path: ./
          pattern: avatar_*
      - name: Prepare output directory
        run: mkdir ./out
      - name: Zip artifacts
        run: |
          for model_file in $(ls -1 | grep 'avatar_')
          do
            cd ./${model_file}
            zip -r ../out/$(echo ${model_file} | sed -e 's/avatar_//').zip ./
            cd ../
          done
      - name: Attach artifacts to release assets
        run: |
          for zip_file in $(ls -1)
          do
            gh release upload ${TAG_NAME} ./${zip_file} --repo ${REPOSITORY}
          done
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          REPOSITORY: ${{ github.repository }}
        working-directory: ./out